using System.Collections.Generic;
using UnityEngine;

//MIGHT BE BEST TO RENAME THIS SCRIPT HUMANOID COMBAT SKILLS
//HAVE A SEPERATE SCRIPT FOR OTHER SKILLS THAT WILL CHECK BODYPARTS FOR BASESKILL - REALTED BODYPART HEALTH
public class Skills : MonoBehaviour
{

}


